import { chromium, devices } from "playwright";
const BASE = "http://localhost:3000";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await b.newContext({ ...devices["iPhone 13"] });
const page = await ctx.newPage();
let fail=0; const ck=(l,ok)=>{console.log(`${ok?"✅":"❌"} ${l}`); if(!ok)fail++;};
const external=[], fontReqs=[], errs=[];
page.on("request", r => { const u=r.url(); if(/fonts\.googleapis|fonts\.gstatic/.test(u)) external.push(u); if(/\.woff2/.test(u)) fontReqs.push(new URL(u).pathname); });
page.on("console", m => { if(m.type()==="error") errs.push(m.text().slice(0,120)); });
await page.goto(`${BASE}/login`);
await page.fill('input[name=email]','tech@apexplumbing.demo');
await page.fill('input[name=password]','demo1234');
await page.click('button[type=submit]');
await page.waitForLoadState("networkidle");
await page.goto(`${BASE}/dashboard`, { waitUntil:"networkidle" }).catch(()=>{});
await page.goto(`${BASE}/field`, { waitUntil:"networkidle" });
await page.waitForTimeout(1500);
ck(`NO external Google Fonts requests (${external.length})`, external.length===0);
ck(`self-hosted woff2 fetched same-origin (${fontReqs.length}: ${fontReqs.slice(0,2).join(", ")})`, fontReqs.length>0 && fontReqs.every(p=>p.startsWith("/_next/")));
const fam = await page.evaluate(()=>getComputedStyle(document.body).fontFamily);
ck(`body font-family resolves to Inter Variable (${fam.slice(0,40)})`, /Inter Variable/.test(fam));
const loaded = await page.evaluate(async ()=>{ await document.fonts.ready; return [...document.fonts].filter(f=>f.status==="loaded").map(f=>f.family); });
ck(`Inter Variable actually loaded (${[...new Set(loaded)].join(", ")})`, loaded.some(f=>/Inter Variable/.test(f)));
ck(`no console errors on field (${errs.length}: ${errs.slice(0,1)})`, errs.length===0);
// offline: fonts cached by SW
await page.evaluate(async()=>{for(let i=0;i<25&&!navigator.serviceWorker.controller;i++)await new Promise(r=>setTimeout(r,200));});
const cachedFonts = await page.evaluate(async()=>{ const ks=await caches.keys(); let n=0; for(const k of ks){const c=await caches.open(k); const rs=await c.keys(); n+=rs.filter(r=>/\.woff2/.test(r.url)).length;} return n; });
ck(`woff2 cached by service worker for offline (${cachedFonts})`, cachedFonts>0);
await b.close();
console.log(fail===0?"\nFONT SELF-HOSTING VERIFIED":`\n${fail} FAILED`);
process.exit(fail===0?0:1);
